import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " EMBERLINE TATTOO STUDIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-950 text-zinc-100">
        <div className="relative min-h-screen overflow-hidden">

          {/* BACKGROUND IMAGE */}
          <div className="absolute inset-0 bg-fixed bg-cover  bg-top-right bg-no-repeat bg-[url('/bg.png')]" />

          {/* DARK OVERLAY */}
          <div className="absolute inset-0 bg-zinc-950/60" />

          <Navbar />
          {/* PAGE CONTENT */}
          <div className="relative z-10">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
